devU-client/src/components/pages/assignmentUpdatePage.tsx, devU-client/src/components/pages/coursesFormPage.tsx, devU-client/src/components/shared/inputs/textField.tsx
I added a course assignment problem creation form to add assignment problems. I created the branch off develop so it won't run with docker. Gives a cannot compile typescript error, not sure if that's what everyone gets. I tested it before I pushed though so it should work fine after that's fixed.
=> Add assignment problem creation form

devU-client/src/components/pages/assignmentDetailPage.tsx, devU-client/src/components/pages/courseAssignmentsListPage.tsx, devU-client/src/components/pages/courseDetailPage.scss, devU-client/src/components/pages/courseDetailPage.tsx, devU-client/src/components/pages/userCoursesListPage.tsx
If it fixes a bug or resolves a feature request, be sure to link to that issue using #{50}.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My changeset covers only what is described above (no extraneous changes)
If this is a relatively large or …
=> added display and submission of assignment problems

devU-api/scripts/populate-db.ts
Adds a function to auto log in when using the populate db script
=> auto login in populate db

devU-api/scripts/populate-db.ts, devU-api/src/entities/deadlineExtensions/deadlineExtensions.controller.ts, devU-api/src/entities/deadlineExtensions/deadlineExtensions.model.ts, devU-api/src/entities/deadlineExtensions/deadlineExtensions.router.ts, devU-api/src/entities/deadlineExtensions/deadlineExtensions.serializer.ts, devU-api/src/entities/deadlineExtensions/deadlineExtensions.service.ts, devU-api/src/entities/deadlineExtensions/deadlineExtensions.validator.ts, devU-api/src/entities/deadlineExtensions/tests/deadlineExtensions.controller.test.ts, devU-api/src/entities/deadlineExtensions/tests/deadlineExtensions.serializer.test.ts, devU-api/src/migration/1709413878786-addDeadlineExtensions.ts, devU-api/src/model/index.ts, devU-api/src/router/index.ts, devu-shared/src/index.ts, devu-shared/src/types/deadlineExtensions.types.ts
Adds deadline extensions endpoint 
=> Submission deadlines endpoint

devU-api/src/entities/submission/submission.controller.ts, devU-api/src/entities/submission/submission.router.ts, devU-api/src/entities/submission/submission.service.ts, devU-api/src/entities/submissionScore/submissionScore.controller.ts, devU-api/src/entities/submissionScore/submissionScore.router.ts, devU-api/src/entities/submissionScore/submissionScore.service.ts, devU-client/src/components/authenticatedRouter.tsx, devU-client/src/components/pages/assignmentDetailPage.tsx, devU-client/src/components/pages/submissionDetailPage.tsx, devU-client/src/components/pages/submissionFeedbackPage.tsx, devU-client/src/components/pages/userSubmissionsListPage.tsx
Added a list of submissions to the assignment detail page. Updated the submission detail view to display the submission's scores and content. Created a submission feedback page to view submission feedback. Also fixed the user submissions list page to only display the user's submissions. Resolves #76 
Currently new submissions don't immediately appear in the assignment submissions list, a …
=> Submission list and detail views

devU-api/src/entities/containerAutoGrader/containerAutoGrader.controller.ts, devU-api/src/entities/containerAutoGrader/containerAutoGrader.service.ts, devU-api/src/entities/course/course.service.ts, devU-api/src/entities/submission/submission.controller.ts, devU-api/src/entities/submission/submission.service.ts, devU-api/src/fileStorage.ts, devU-api/src/fileUpload/fileUpload.controller.ts, devU-api/src/fileUpload/fileUpload.service.ts, devU-api/src/utils/fileUpload.utils.ts
1. Finished #82 to add a function support download files from minio for grader entity to create the container. 
2. Fixed bug #81 where fileModel stores wrong information to the database. and also changing the naming function for the minio bucket name to avoid name length overflow.
3. Update nameGenerate function, adding the current userId to avoid having the same name if different users submit a same file at the same time.
4. Restore listByAssignmentId function due to grader.service entity has not updated yet( need to change to the new function)
5. Fixed previous conflicts in submission.controller caused the program crash
_Put an `x` in the …
=> Submission fixed up & CAG function to support file download

devU-api/scripts/populate-db.ts, devU-api/src/auth/login.developer/login.developer.controller.ts, devU-api/src/entities/grader/grader.service.ts, devU-client/src/components/pages/assignmentDetailPage.tsx, devU-client/src/components/pages/submissionDetailPage.tsx, devU-client/src/components/pages/submissionFeedbackPage.tsx
Misc changes and fixes to prepare for the sprint 3 demo. 
=> Sprint 3 cleanup

devU-api/src/entities/containerAutoGrader/containerAutoGrader.controller.ts, devU-api/src/entities/containerAutoGrader/containerAutoGrader.model.ts, devU-api/src/entities/containerAutoGrader/containerAutoGrader.router.ts, devU-api/src/entities/containerAutoGrader/containerAutoGrader.service.ts, devU-api/src/entities/submission/submission.controller.ts, devU-api/src/entities/submission/submission.model.ts, devU-api/src/entities/submission/submission.router.ts, devU-client/src/components/authenticatedRouter.tsx, devU-client/src/components/pages/assignmentDetailPage.tsx, devU-client/src/components/pages/containerAutoGraderForm.tsx, devU-client/src/components/pages/submissionDetailPage.tsx, devU-client/src/components/pages/submissionFeedbackPage.tsx, devU-client/src/services/request.service.ts
Created a new form to create container autograders and added a file upload field to the submission creation form. Added postMultipart and putMultipart functions to RequestService to make multipart-form requests.
As an assignment can only have a single container autograder, a way to update CAGs should be implemented on the frontend.
Notable bug, as the handling of query parameters has changed on …
=> Frontend file upload

devU-api/scripts/populate-db.ts, devU-api/src/entities/containerAutoGrader/containerAutoGrader.service.ts, devU-api/src/entities/course/course.service.ts, devU-api/src/entities/submission/submission.service.ts
update populateDB to reduce the redundant code: creating functions for it. 
update populateDB to store every user's authToken to specify the submitter. (#89)
fixed bug for bucket naming creation. (#90)
update the containerAutoGrader entity, adding the correct UserId to fileModel (courseId still needs to be finished).
=> Populate db

devU-client/src/components/pages/courseDetailPage.scss, devU-client/src/components/pages/courseDetailPage.tsx
Updated the Course Detail page to have a basic design matching FIgma
Resolves #93 
=> Course detail page

devU-client/src/components/misc/globalToolbar.tsx, devU-client/src/components/pages/courseAssignmentsListPage.tsx, devU-client/src/components/pages/homePage.tsx, devU-client/src/components/pages/userCoursesListPage.tsx, devU-client/src/components/utils/roleToggle.tsx, devU-client/src/redux/initialState/index.ts, devU-client/src/redux/reducers/index.ts, devU-client/src/redux/role.redux.ts, devU-client/src/redux/store.ts
Adds a toggle on navbar at the top of the page. The value is manged using redux in ```devU-client/src/redux/role.redux.ts```, the final value is also stored in localstorage for persistence between page switches and reloads
For now the toggle can hide create buttons on the courses and assignments page.
If any page needs to access the role they can easily access this using 
```
const role = useAppSelector((store) => store.roleMode)
```
which will give them access to the role value and a utility function isInstructor
e.g.
```
role.userRole // access the value itself
or
role.isInstructor() // utility function which returns true if toggled to instructor
``` …
=> Added Role toggle

devU-client/src/components/pages/assignmentDetailPage.scss, devU-client/src/components/pages/assignmentDetailPage.tsx
Updated the assignment detail page. Changed the styling and updated the api calls to match the newest versions. However, the requests seem to give back a 404 error so there may be some error in the backend?... or maybe I missed something.
Updated the Assignment Detail Page to be better styled than it currently was. It was very ugly looking so it was not hard :( .
Resolves #104 
=> Updated Assignment Detail Page

devU-client/src/components/shared/inputs/textField.tsx
Text fields were previously not readable in dark mode due to very low contrast against background. Added styling to the textfield component to make it readable against dark backgrounds and change on theme toggle.
them, don't hesitate to ask. This is simply a reminder of what we are going to look for before …
=> textfield readability fix

devU-client/src/assets/variables.scss, devU-client/src/components/pages/courses/courseDetailPage.tsx, devU-client/src/components/pages/homePage/homePage.tsx
I have added an confirmation popup for the user to confirm if they want to drop a course or not 
- [ x] My changeset covers only what is described above (no extraneous changes) …
=> Added the confirmation pop-up to handledrop function in coursedetails

devU-client/package.json, devU-client/src/components/pages/forms/assignments/assignmentFormPage.scss, devU-client/src/components/pages/forms/assignments/assignmentFormPage.tsx, devU-client/src/components/shared/inputs/textField.scss, devU-client/src/components/shared/inputs/textField.tsx, devU-client/src/components/utils/dragDropFile.scss, devU-client/src/components/utils/dragDropFile.tsx
Updated the Assignment Creation Page to better match the Figma design.
Fixes #132 
There is an attachments section for this form that currently has no purpose as the backend does not support file uploads/attachments for creating assignments.
=> 56 assignment creation page

devU-api/package.json, devU-api/src/entities/assignment/assignment.controller.ts, devU-api/src/entities/assignment/assignment.model.ts, devU-api/src/entities/assignment/assignment.router.ts, devU-api/src/entities/assignment/assignment.serializer.ts, devU-api/src/entities/assignment/assignment.service.ts, devU-api/src/fileStorage.ts, devU-api/src/migration/1728881406096-assignmentAttachment.ts, devU-client/package.json, devU-client/src/components/pages/forms/assignments/assignmentFormPage.scss, devU-client/src/components/pages/forms/assignments/assignmentFormPage.tsx, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.tsx, devU-client/src/components/shared/inputs/textField.scss, devU-client/src/components/shared/inputs/textField.tsx, devU-client/src/components/utils/dragDropFile.scss, devU-client/src/components/utils/dragDropFile.tsx, devU-shared/src/types/assignment.types.ts, docker-compose.yml
Added file attachment support to assignments endpoint. it supports up to 5 files and each file has a limit of 5 MB
Added a new endpoint to download attachments.
I merged #133 since I needed the UI for the assignment creation page for testing.
=> Assignment up

devU-client/src/components/misc/navbar.scss, devU-client/src/components/misc/navbar.tsx, devU-client/src/components/pages/assignments/assignmentDetailPage.scss, devU-client/src/components/pages/assignments/assignmentDetailPage.tsx, devU-client/src/components/pages/homePage/homePage.scss, devU-client/src/components/pages/homePage/homePage.tsx
…options section for the buttons to be placed next to the assignment, I added the description of the assignment as well in the assignment section. I also fixed the nav bar for the breadcrumbs, to be more uniform
I have updated the styling for the assignment details page for instructor as well as fixing the breadcrumbs for the nav bar to look more uniform, this is for issue #143 
_Put an `x` in the boxes that apply. You can …
=> added styling to the assignment details page for instructor and nav bar breadcrumbs 

devU-api/src/entities/assignment/assignment.controller.ts, devU-api/src/entities/assignment/assignment.service.ts, devU-api/src/entities/submission/submission.middleware.ts, devU-api/src/entities/submission/submission.router.ts, devU-api/src/entities/submission/submission.service.ts, devU-api/src/entities/submission/submission.validator.ts, devU-api/src/fileUpload/fileUpload.controller.ts
Added checks for max submissions and file size, end date and disable handins
Also changed how files are retrieved, previously it was json serializing it which was unnecessary as it was returning only a file, now we directly serve the file contents.
=> enforce max submissions for assignment

devU-client/src/components/pages/forms/courses/courseUpdatePage.tsx, devU-client/src/components/pages/forms/courses/coursesFormPage.scss, devU-client/src/components/pages/forms/courses/coursesFormPage.tsx
Closes #152 
Updated the styling of the create course form
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution …
=> 89 create course styling

devU-client/src/components/pages/forms/assignments/assignmentFormPage.tsx, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.scss, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.tsx, devU-client/src/components/pages/homePage/homePage.scss, devU-client/src/components/shared/inputs/textField.tsx, devU-client/src/components/utils/dragDropFile.scss, devU-client/src/components/utils/dragDropFile.tsx, devU-client/src/utils/theme.utils.ts, devU-shared/src/types/assignment.types.ts
Updated this page to add functionality for :
- Updating current assignment info
- Creating Problems
- Editing Problems
- Editing attachments
Updates styling of the edit assignment page
fixes #151 
It was explained to me that editing attachments wipes all previous files. Add warnings in the future.
=> Updated the Assignment Edit page

devU-api/src/entities/user/user.service.ts, devU-api/src/entities/userCourse/userCourse.controller.ts, devU-api/src/entities/userCourse/userCourse.router.ts, devU-api/src/entities/userCourse/userCourse.service.ts
Added 2 endpoints, both accept a list of emails in a json array and add/drop them, returns errors if failed.
All users are added as students
`/courses/{courseId}/students/add`
`/courses/{courseId}/students/drop`
=> added bulk enroll/drop students

devU-client/src/components/misc/globalToolbar.scss, devU-client/src/components/misc/navbar.scss, devU-client/src/components/pages/homePage/homePage.scss, devU-client/src/components/pages/homePage/homePage.tsx, devU-client/src/components/pages/submissions/submissionDetailPage.scss, devU-client/src/components/pages/submissions/submissionDetailPage.tsx
Updating the student's submissions page styling for issue #155.  
- [ x ] New feature (non-breaking change which adds functionality)
If this is a relatively large or complex …
=> Task 86 update for student's submissions page

devU-client/src/components/pages/forms/courses/coursesFormPage.tsx
Fixed minor bug for the create course form: after submitting the form it would subtract a day when shown on the My Courses page. 
If this is a relatively large or complex …
=> fixed subtracting a day from start and end date

devU-api/src/entities/user/user.controller.ts
Fixed syntax error for try/catch in from resolving previous PR in userCourse _deleteUser function
If this is a relatively large or complex change, kick off the discussion by …
=> fixed try/catch syntax error in userCourse _deleteUser function

devU-api/src/entities/user/user.controller.ts, devU-api/src/entities/userCourse/userCourse.controller.ts
revert user.controller.ts to previous working state and update userCourse.controller.ts to fix missing catch
If this is a relatively large or complex change, kick off the …
=> revert user.controller.ts to previous working state 

devU-client/src/components/listItems/simpleAssignmentListItem.scss, devU-client/src/components/listItems/userCourseListItem.scss, devU-client/src/components/pages/assignments/assignmentDetailPage.scss, devU-client/src/components/pages/assignments/assignmentDetailPage.tsx, devU-client/src/components/pages/forms/assignments/assignmentFormPage.scss, devU-client/src/components/pages/forms/assignments/assignmentFormPage.tsx, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.scss, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.tsx, devU-client/src/components/pages/homePage/homePage.scss, devU-client/src/components/pages/homePage/homePage.tsx, devU-client/src/components/pages/submissions/submissionDetailPage.scss, devU-client/src/components/pages/submissions/submissionDetailPage.tsx, devU-client/src/components/shared/layouts/pageWrapper.scss
Restyling for pages to fix spacing, color themes
=> Task 105 fixing styling each page on course website

devU-client/src/components/pages/forms/courses/courseUpdatePage.tsx
Changed add/drop to use bulk endpoint
=> updated to use bulk add/drop students endpoints

devU-api/package.json, devU-api/src/entities/webhooks/webhooks.controller.ts, devU-api/src/entities/webhooks/webhooks.middleware.ts, devU-api/src/entities/webhooks/webhooks.model.ts, devU-api/src/entities/webhooks/webhooks.router.ts, devU-api/src/entities/webhooks/webhooks.serializer.ts, devU-api/src/entities/webhooks/webhooks.service.ts, devU-api/src/entities/webhooks/webhooks.validator.ts, devU-api/src/index.ts, devU-api/src/migration/1730698767895-webhooks.ts, devU-api/src/router/courseData.router.ts, devU-client/src/components/authenticatedRouter.tsx, devU-client/src/components/pages/courses/courseDetailPage.tsx, devU-client/src/components/pages/webhookURLForm.scss, devU-client/src/components/pages/webhookURLForm.tsx, devU-shared/src/index.ts, devU-shared/src/types/webhooks.types.ts
Added styling to the webhooks form I created.
This branch contains code pulled from Rishi's webhooks branch.
fixes #173 
=> 119 webhooks styling

devU-api/src/entities/assignment/assignment.service.ts, devU-client/src/components/pages/forms/courses/automateDates.tsx, devU-client/src/components/pages/forms/courses/courseUpdatePage.tsx, devU-client/src/components/pages/forms/courses/coursesFormPage.scss, devU-client/src/components/pages/forms/courses/coursesFormPage.tsx
Added default start and end dates for semester selection in frontend. Added filter for assignment release date in backend.
Closes #180 
Closes #179 
- [] Lint and unit tests pass locally with my changes
=> 110 automate start/end dates

devU-client/src/components/pages/assignments/assignmentDetailPage.tsx, devU-client/src/components/pages/assignments/scoreboard.scss, devU-client/src/components/pages/assignments/scoreboard.tsx, devU-client/src/components/pages/courses/courseDetailPage.scss, devU-client/src/components/pages/courses/courseDetailPage.tsx, devU-client/src/components/pages/forms/containers/nonContainerAutoGraderForm.tsx, devU-client/src/components/pages/gradebook/gradebookInstructorPage.tsx, devU-client/src/components/pages/homePage/homePage.tsx, devU-client/src/components/pages/submissions/submissionDetailPage.tsx
I allowed the course button to be pressed on, removed the unnecessary course drop down, added a scoreboard with dummy data
If this is a relatively large or complex change, …
=> Remove unnecessary drop down for assignments/ course button can be pressed on anywhere

devU-client/src/components/pages/assignments/assignmentDetailPage.tsx, devU-client/src/components/pages/courses/courseDetailPage.scss, devU-client/src/components/pages/courses/courseDetailPage.tsx, devU-client/src/components/pages/gradebook/gradebookInstructorPage.tsx, devU-client/src/components/pages/homePage/homePage.scss, devU-client/src/components/pages/homePage/homePage.tsx, devU-client/src/components/pages/submissions/InstructorSubmissionspage.tsx
Updating the submission page by implementing a scoreboard to the bottom of the page. Using dummy data for an approximate runtime, score, ubit.
- [ x] New feature (non-breaking change which adds functionality)
them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging …
=> 133 create a scoreboard and implement design on frontend

devU-api/src/entities/assignment/assignment.service.ts
Removed assignment filtering for sprint grading
=> removed assignment filter by start date from backend

devU-api/src/entities/submission/submission.controller.ts, devU-client/src/components/pages/webhookURLForm.tsx
There was a bug when making submissions, where the userId was not being passed. this fixes it 
=> fix-submissions

devU-api/src/migration/1731177885475-add-sticky-notes.ts
Added file to create the sticky-notes table. Fixed the issue with other migration file trying to add columns to a table that did not exist.
=> Added file to create the sticky-notes table

devU-client/src/assets/global.scss, devU-client/src/assets/variables.scss, devU-client/src/components/listItems/simpleAssignmentListItem.scss, devU-client/src/components/listItems/userCourseListItem.scss, devU-client/src/components/listItems/userCourseListItem.tsx, devU-client/src/components/misc/globalToolbar.scss, devU-client/src/components/misc/navbar.scss, devU-client/src/components/pages/forms/assignments/assignmentFormPage.scss, devU-client/src/components/pages/forms/assignments/assignmentFormPage.tsx, devU-client/src/components/pages/gradebook/gradebookInstructorPage.tsx, devU-client/src/components/pages/gradebook/gradebookPage.scss, devU-client/src/components/pages/gradebook/gradebookStudentPage.tsx, devU-client/src/components/pages/homePage/homePage.scss, devU-client/src/components/pages/homePage/homePage.tsx, devU-client/src/components/shared/layouts/pageWrapper.scss, devU-client/src/components/utils/dragDropFile.scss
=> 145 redesign pages

devU-client/src/components/pages/assignments/assignmentDetailPage.tsx, devU-client/src/components/pages/courses/courseDetailPage.tsx
removing the submit button from assignments that are past the due date
- [ X] Bugfix (non-breaking change which fixes an issue)
- [X ] My changeset covers only what is described above (no …
=> removing the submit button from assignments that are past the due date

api.Dockerfile, devU-api/package.json, devU-api/src/entities/containerAutoGrader/containerAutoGrader.controller.ts, devU-api/src/entities/containerAutoGrader/containerAutoGrader.router.ts, devU-api/src/entities/containerAutoGrader/containerAutoGrader.service.ts, devU-api/src/entities/grader/grader.service.ts, devU-api/src/entities/userCourse/userCourse.controller.ts, devU-api/src/entities/userCourse/userCourse.router.ts, devU-api/src/entities/userCourse/userCourse.service.ts, devU-api/src/router/courseData.router.ts
fixes some bugs reported
resolves #212 
implements #213 
removed /categories from the router since the assignment already contains the category info
=> 67 bug fixes

devU-client/src/components/pages/forms/containers/containerAutoGraderForm.scss, devU-client/src/components/pages/forms/containers/containerAutoGraderForm.tsx
=> 65 updated add grader code modal

devU-client/src/assets/global.scss, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.tsx, devU-client/src/components/pages/forms/assignments/textProblemModal.tsx, devU-client/src/components/pages/forms/courses/createCourseModal.tsx, devU-client/src/components/shared/layouts/modal.tsx
Updated adding text problems so that the problem and grader are created from one form submission when adding text problem. 
Closes #224 
=> #62 - Implement adding text problem modal

devU-client/src/components/pages/assignments/assignmentDetailPage.scss, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.scss
Title basically, just forgot to add align-items center to some divs containing buttons.
=> Fixed weirdly tall buttons on edit assignment and assignment detail pages

devU-client/src/components/pages/forms/containers/containerAutoGraderForm.scss
=> Dev into main

devU-client/src/assets/global.scss, devU-client/src/components/authenticatedRouter.tsx, devU-client/src/components/misc/footer.scss, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.scss, devU-client/src/components/pages/submissions/manualGradeModal.tsx, devU-client/src/components/pages/submissions/submissionDetailPage.scss, devU-client/src/components/pages/submissions/submissionDetailPage.tsx, devU-client/src/components/shared/layouts/pageWrapper.scss, devU-client/src/components/shared/layouts/pageWrapper.tsx
Redesigned assignment detail page to clearly view problem scores, autograder feedback, and instructor feedback. Added modal for manual grading. Rendered feedback preserves newline characters and whitespace.
**Extraneous changes**: footer positioning changed from bottom of viewport to bottom of content
Closes #232 
If this is a relatively large or complex change, kick off the discussion by …
=> 71 view feedback

devU-client/src/components/authenticatedRouter.tsx, devU-client/src/components/misc/footer.scss, devU-client/src/components/pages/assignments/assignmentDetailPage.tsx, devU-client/src/components/pages/forms/assignments/assignmentFormPage.scss, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.tsx, devU-client/src/components/pages/forms/assignments/codeProblemModal.tsx, devU-client/src/components/pages/forms/assignments/multipleChoiceModal.tsx, devU-client/src/components/pages/forms/assignments/textProblemModal.tsx, devU-client/src/components/pages/forms/containers/containerAutoGraderModal.tsx, devU-client/src/components/shared/inputs/button.tsx, devU-client/src/components/shared/layouts/modal.tsx, devU-client/src/components/shared/layouts/pageWrapper.scss
Added a modal for creating mulitple choice questions. At the moment it's hard set to 5 answer options and only one correct answer, but in the future we'll probably want to make multiple answers toggleable and increase/decrease options (something like 2-5 might make sense)
- Made some changes to padding for the footer, renamed Sameep's modal file to match repo standard
=> 83 - Multiple Choice modal

devU-client/src/components/pages/submissions/manualGradeModal.tsx, devU-client/src/components/pages/submissions/submissionDetailPage.tsx
Individual problems in a submission can be manually graded from the manual grading modal on the view feedback page for assignment submissions. 
=> 81 - Manually grade problems

devU-client/src/components/pages/forms/assignments/assignmentFormPage.tsx, devU-client/src/components/pages/forms/assignments/assignmentUpdatePage.tsx
Quick fix to make multiple choice questions appear on edit assignment page :D
=> fixed problems not showing up when created
